### PR TITLE
Common URI utility methods

### PR DESCRIPTION
**Pull request by Tobion**
This PR adds common utility methods for URIs.

Those methods are based on RFC 3986 with links to the spec.

- `Uri::isDefaultPort`
- `Uri::isAbsolute`
- `Uri::isNetworkPathReference`
- `Uri::isAbsolutePathReference`
- `Uri::isRelativePathReference`
- `Uri::isSameDocumentReference`
- `Uri::composeComponents`
- `UriNormalizer::normalize`
- `UriNormalizer::isEquivalent`
- `UriResolver::relativize`

Putting all the static methods in the `Uri` class made it too crowded, especially with the constants for the normalizer. So instead new classes `UriNormalizer` and `UriResolver` were created to logically group methods. Due to that `Uri::resolve` and `Uri::removeDotSegments` have been deprecated and moved to the `UriResolver`.

I'm pretty proud of the `relativize` method as it was pretty complex to get right for all edge cases. It is highly tested. A similar method also exists in (java)[https://developer.android.com/reference/java/net/URI.html#relativize(java.net.URI)] but is much less sophisticated as the java solution does not support to travel the hierarchical URI upwards with dot-segments.

Todo
- [x] tests for some methods are missing
- [x] the phpdoc is already good. but `readme.md` needs update
- [x] optionally add Percent-Encoding Normalization: https://tools.ietf.org/html/rfc3986#section-6.2.2.2

### CODE REVIEW

**Comment by Tobion** [comment]
@mtdowling this is ready. Could you please review?

**Comment by jeremeamia** [comment]
I'll try to review this as well in the next couple of days. Looks cool though.

**Comment by Tobion** [comment]
@jeremeamia I'd be happy to get your feedback

**Comment by jeremeamia** [comment]
I looked through this for about a half hour last night. It looks good to me. Nice additions.

**Comment by Tobion** [comment]
Thanks. Can I merge then?

**Comment by mtdowling** [comment]
Good work! 🚢

**Comment by Tobion** [comment]
Added explanation for workaround #111 and I also added a normalization for the file default host.

**Pull request merged**
