### PR TITLE
Require php 5.6

### PR DESCRIPTION
**Pull request by Tobion**
My proposal is to release #97 as version 1.4. And after that require PHP 5.6 for the next version 1.5.
PHP 5.5 is now EOL as well.

### CODE REVIEW

**Comment by mtdowling** [comment]
What's the motivation here for the bump to 5.5? We'd be leaving a large number of users behind here, including Guzzle users, AWS SDK for PHP users, and many others. It doesn't seem like a good idea to maintain two versions of the Guzzle PSR-7 library (one of 5.5 and one for 5.6), so this PR would essentially mean the PSR-7 dependency for these users would be frozen after the next update.

**Comment by GrahamCampbell** [comment]
:-1: We should stay on 5.5. Guzzle is widely used, and that is put at risk by bumping the PHP version when we don't need to.

**Comment by Tobion** [comment]
Currently it is even still compatible with 5.4, not 5.5. The motivation is to make use of newer stuff like array constants.

> so this PR would essentially mean the PSR-7 dependency for these users would be frozen after the next update

That is not a problem IMO as everything after now are optional features and are not necessary to comply with PSR-7. And if there is an urgent bugfix that is needed for guzzle for example, we can easily backport that to the php 5.4 version. But I doubt this will be necessary.

**Comment by mtdowling** [comment]
I have no issue with bumping to 5.5 given that Guzzle already uses 5.5 (and Guzzle is the dominant consumer of this package).

I don't see a strong motivation in bumping to 5.6 though. 5.6 offers very few benefits over 5.5 that would warrant it as a minimum requirement when weighed against the number of consumers we'd be leaving behind. For example, roughly 34% of the User-Agent headers sent through the AWS SDK for PHP show that they are on PHP 5.5.

**Comment by GrahamCampbell** [comment]
We should stay on PHP 5.5 rather than 5.6 IMO. The only difference I can see here is the availability of arrays as constants.

**Comment by Tobion** [comment]
I'm ok to switch to 5.5 but I don't get why libraries are often afraid to bump their requirements. Even php 5.4 users can still use it in this case. And I don't see the point in supporting EOL php versions when not needed. I mean at some point we want to bump the requirement anyway. What is the difference between doing it now and maybe in 6 months or 1 year?

**Comment by GrahamCampbell** [comment]
Not all libraries are just targeting people who can upgrade to newer PHP versions. Often larger companies (or even not very large ones) will not upgrade, and thus people need to support them.

**Comment by Tobion** [comment]
Again, this is about new features. You are basically assuming there will be new features in the future that need to be used by people that use outdated php versions. How long do you think we need to develop with this assumption?

**Comment by Tobion** [comment]
I think it's now even more safe to require php 5.6 as php 5.5 is long outdated.

**Comment by Tobion** [comment]
@mtdowling are you still not confident to bump the requirement to 5.6?

**Comment by jeremeamia** [comment]
Still hesitant on this, but not opposed as long as Guzzle doesn't require the PHP 5.6+ version. @mtdowling should weigh in on any impact to AWS SDK though.

**Comment by sagikazarmark** [comment]
This would mean that Guzzle won't receive PSR-7 fixes from now on. This package is tightly coupled to Guzzle, so either we should make a commitment to drop support for 5.5 in Guzzle soon.

Alternatives would be releasing a new major version and backporting fixes to the 1.x branch.

I would say just dropping 5.6 without any of the above would lead to confusion. (The list of actively used Guzzle versions (4-5-6) already cause a lot of confusion and the PHP version differences could create a confusion-matrix together with those Guzzle versions)

**Comment by Tobion** [comment]
HHVM tests should work with version 3.19 but that doesn't seem installable on travis yet. Its missing in http://dl.hhvm.com/ubuntu/dists/

**Comment by kstich** [comment]
13% of users of the AWS SDK for PHP are using PHP 5.5. While that’s definitively less than the ~34% reported last year, it’s still a significant number of our customers. With this information, we are not comfortable increasing our minimum version requirement at this time, and it would be disappointing if we were no longer able to receive bug fixes to this PSR-7 package. If this package is to be updated, we would prefer to see a solution similar to what @sagikazarmark proposed: a new major version that subsequent dependencies can hold to, along with a commitment to porting bug fixes back into the existing PHP 5.4 code base. Another benefit of this approach is that this new major version could also serve as an opportunity to do some minor cleanup and refactoring.

**Comment by sagikazarmark** [comment]
@kstich Although I understand your concerns (and honestly would like to find a way that benefits everyone) I also think that we need to draw a line somewhere.  PHP 5.5 does not receive security fixes anymore and from 2019 the PHP 5.x branch won't receive any updates.

http://php.net/supported-versions.php

So while for now I think we should provide as much support for these PHP versions as well, I would like to see a roadmap including a rough estimate from which point we can drop support for at least 5.5. For the long term I think a possible Guzzle 7 version will drop support for PHP 5.x entirely meaning the last two supported versions of Guzzle (6.x, 7.x) will receive support for 5.x (Guzzle 6), preferably 5.6 and 7.x (Guzzle 7).

**Comment by sagikazarmark** [comment]
Another year passed and with PSR-17 and PSR-18 we are forced to bump version to 7.x anyway, so I think we can close this PR and leave the 1.x branch as is.

**Comment by Tobion** [comment]
Yeah good point. Let's jump straight to php 7.0. Also php 5.6 is eof soon as well.

**Pull request closed without merging**
