### PR TITLE
Uri properties private access

### PR DESCRIPTION
**Pull request by m-ark22**
Sorry, could you explain how it works?
$new = clone $this;
$new->host = $host;
Cloned object can assign a value to a private member?

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Visibility is defined on the class level, not on the object instance level.

So to properly phrase the question: An instance of a class can assign a value to a private member of an object of the same class? Yes, it can.

**Comment by m-ark22** [comment]
Understood, thanks

**Comment by m-ark22** [comment]
I suppose there is another problem. The method returns a cloned $ this that can access private properties. Then the class becomes mutable. Is this the correct behavior? Or I misunderstood again?

**Comment by sagikazarmark** [comment]
Technically there is no immutability in PHP. It's achieved by using private members and accessor methods (get, with).

With methods return new instances and although the object is modified internally, you can't actually modify anything using publicly accessable members/methods which gives us kind of an emulation of immutability.

Of course you can still bypass this using reflection, but it's considered black magic.

So you are partly right: the state is mutable internally, but there is no publicly mutable state.

I suggest reading the original PSR-7 standard meta and the related blog posts for further explanation.

**Comment by m-ark22** [comment]
Thanks, nevertheless, maybe I put it wrong. I meant the following:
$new = $uri->withHost('example.com');
$new->host = 'another.example.com'; // There should be no exception, but it is expected

**Comment by m-ark22** [comment]
Sorry, there is exception

**Comment by sagikazarmark** [comment]
In the above example you try to access a private member outside of the class. It won't work.

**Comment by m-ark22** [comment]
Got it, thanks

**Pull request closed without merging**
