### PR TITLE
Merge v1 before static methods

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Merges 1.x -> master up to the 0cddfcbdb4e0a078adf1794f68de79a57f4fb352 commit on 1.x, and also cherry-picks in 25f7f893f0b52b7b14e244a16679d72b1f0088de. After this PR is merged and so is https://github.com/guzzle/psr7/pull/370, then master should be green. I will then tackle merging the rest of the changes from 1.x into master.

---

EDIT: Changes from https://github.com/guzzle/psr7/pull/370 now included in here too.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
The fix for phpstan is included in https://github.com/guzzle/psr7/pull/370.

**Comment by Nyholm** [comment]
The diff is super small

**Comment by GrahamCampbell** [comment]
Yes. This only merges things before the static method changes. I'll handle that after this PR and the other is merged.

**Review by Nyholm — APPROVED** [review]
Thank you

**Pull request merged**
