### PR TITLE
change static vars to const and add const visibility

### PR DESCRIPTION
**Pull request by Tobion**

### CODE REVIEW

**Comment by Tobion** [comment]
Someone please review

**Comment by gmponos** [comment]
May I ask, because I was always wondering about it.. what are the benefits of the one over the other way?

**Comment by Tobion** [comment]
static vars was only a workaround because PHP didn't support private constants and array constants in earlier versions.
The PR got closed because 2.x got deleted. Reopened in #281

**Comment by gmponos** [comment]
> The PR got closed because 2.x got deleted. Reopened in #281

This was unexpected? I thought that ppl can change their target branch. Do they all need to reopen their PRs?

**Comment by Tobion** [comment]
Didn't know that either and I couldn't change the target branch.

**Pull request closed without merging**
