### PR TITLE
CS fixes

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This will allow me to more easily compare the tests in the 1.x and master branch, when I do the merge.

**Comment by Nyholm** [comment]
If we have plans to put this branch to "security fixes only", then I suggest to not merge this. Instead we should do a similar fix for 2.x

**Comment by GrahamCampbell** [comment]
This is already fixed on 2.x. This is why I want to do it on 1.x too, so I can merge the two branches easily. :)

**Comment by Nyholm** [comment]
Oh. Okey. Smart. So I assume you copied the config and just ran the php-cs-fixer tool

**Comment by GrahamCampbell** [comment]
Yes. I just had to remove a few things from the config file which broke PHP 5.4 syntax. Like short list syntax.

**Review by Nyholm — APPROVED** [review]
If so. I'm happy with this.

**Comment by GrahamCampbell** [comment]
:shipit:

**Pull request merged**
