### PR TITLE
Add support SOH symbol to assert of MessageTrait

### PR DESCRIPTION
**Pull request by bullder**
I noticed quite common behaviour as described in commentary  https://github.com/guzzle/psr7/issues/489#issuecomment-1080758509

But I noticed that in my googleAnalytics cookie exists SOH symbol which is not allowed with current regular expression

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
I don't think that character is permitted according to the HTTP spec?

**Comment by TimWolla** [comment]
> I don't think that character is permitted according to the HTTP spec?

It most certainly is not. And neither is it a valid cookie value according to RFC 6265#4.1.1-

**Comment by TimWolla** [comment]
@bullder What you are attempting there is certainly not an appropriate fix either; where exactly is that broken header coming from for you? Can you give a real-world reproducer script and a full stack trace, please?

**Comment by bullder** [comment]
Good question how to reproduce it. I tried to create cookie with this symbol '\x01' but I wasn't able to realise how is that possible. I thought might be as an idea to simply omit cookie with invalid value 

So technically incorrect value was `"___utmvaPNBuPVKNZ=iut\x01Eevq; path=/; Max-Age=900" is not valid header value`

and stack trace was like 

```
#0 /app/vendor/guzzlehttp/psr7/src/MessageTrait.php(203): GuzzleHttp\Psr7\Response->assertValue() 
#1 [internal function]: GuzzleHttp\Psr7\Response->GuzzleHttp\Psr7\{closure}() 
#2 /app/vendor/guzzlehttp/psr7/src/MessageTrait.php(206): array_map() 
#3 /app/vendor/guzzlehttp/psr7/src/MessageTrait.php(175): GuzzleHttp\Psr7\Response->trimAndValidateHeaderValues() 
#4 /app/vendor/guzzlehttp/psr7/src/MessageTrait.php(148): GuzzleHttp\Psr7\Response->normalizeHeaderValue() 
#5 /app/vendor/guzzlehttp/psr7/src/Response.php(107): GuzzleHttp\Psr7\Response->setHeaders() 
#6 /app/vendor/guzzlehttp/guzzle/src/Handler/EasyHandle.php(81): GuzzleHttp\Psr7\Response->__construct() 
#7 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(565): GuzzleHttp\Handler\EasyHandle->createResponse() 
#8 [internal function]: GuzzleHttp\Handler\CurlFactory->GuzzleHttp\Handler\{closure}() 
#9 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(128): curl_multi_exec() 
#10 /app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(145): GuzzleHttp\Handler\CurlMultiHandler->tick() 
#11 /app/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Handler\CurlMultiHandler->execute() 
#12 /app/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn() 
#13 /app/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending() 
#14 /app/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList() 
#15 /app/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending() 
#16 /app/src/BookingBundle/Provider/Activity/ActivityProvider.php(317): GuzzleHttp\Promise\Promise->wait() 
#17 /app/src/BookingBundle/Provider/Activity/ActivityProvider.php(100): BookingBundle\Provider\Activity\ActivityProvider->runAsyncSearches() 
#18 /app/src/BookingBundle/Controller/SearchController.php(116): BookingBundle\Provider\Activity\ActivityProvider->provideList() 
#19 /app/vendor/symfony/http-kernel/HttpKernel.php(158): BookingBundle\Controller\SearchController->searchActivitiesAction() 
#20 /app/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw() 
#21 /app/vendor/symfony/http-kernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle() 
#22 /app/public/index.php(27): Symfony\Component\HttpKernel\Kernel->handle() 
#23 {main}
```

**Comment by TimWolla** [comment]
> #18 /app/src/BookingBundle/Controller/SearchController.php(116): BookingBundle\Provider\Activity\ActivityProvider->provideList()

BookingBundle is specific to your app, thus we can't know what URL is requested and returning the incorrect headers. It **might** be a bug in Guzzle itself (but I doubt that without a standalone reproducer), but it definitely is not a bug in guzzle/psr7, because the validation is working as expected.

**Comment by TimWolla** [comment]
> My assumption that this value comes from cookie which set by Google Analytics because prefix of cookie hints directly at this source of cookie

- If the endpoint you're hitting is an internal service, then fix this internal service to not send broken cookies.
- If the endpoint you're hitting is **_not_** a publicly available service, then I'd be interested in the URL so that I can take a look at it myself to confirm whether it is a bug in the service or a bug in Guzzle.

**Comment by GrahamCampbell** [comment]
Happy to leave this open, so we don't lose track of this. :)

**Comment by GrahamCampbell** [comment]
Friendly ping @bullder. :)

**Comment by flexponsive** [comment]
This problem also occurs with the API of a major financial exchange, where the Set-Cookie header value (sometimes) contains invalid characters.

According to their support,
> The API is protected from cyber-attacks by a framework called Imperva.
> One of the mechanisms involves the use of malformed cookies to identify malicious bots
> This means that the invalid character is intentional and has to be ignored.

With the current implementation in `MessageTrait`, it is not possible to consume this API.

**Having an option to ignore headers with invalid characters would be very valuable.**

**Comment by GrahamCampbell** [comment]
I stress in the strongest possible terms that Google Analytics is not an HTTP server if it is not following the spec, so it would not be expected that Guzzle should be able to talk to it.

**Comment by bullder** [comment]
Good catch @flexponsive . Actually we also use Imperva.
I would not believe that it is possible but I can observe this issue by my own eyes. Still have no idea how browser clients cookies appears during handling response with guzzle

**Comment by TimWolla** [comment]
Additional detail: https://stackoverflow.com/a/62407633/782822

**Pull request closed without merging**
