### PR TITLE
Soft-final all classes that are final in 2.x

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by Nyholm** [comment]
Hm.. If the "soft final" should be as strict as a `final`, but just technically different... then this is a BC break just as adding the `final` keyword... 

I dont think we can do this.

**Comment by GrahamCampbell** [comment]
We did this in Guzzle 7 in preparation for Guzzle 8: https://github.com/guzzle/guzzle/pull/2726. This is also something Symfony does, and doesn't consider it a BC break: https://github.com/symfony/symfony/pull/35402/files.

**Comment by GrahamCampbell** [comment]
I think while it is technically a BC break if we are being super duper strict, I think it's one we want, and it will help people with upgrading, if they get told off by their static analyzers. I view this as them being told that extending the class is now deprecated, so this is as much as a BC break as adding a deprecated annotation to a method IMO.

**Review by Nyholm — APPROVED** [review]
Fair enough. Thank you for your research.

**Pull request merged**
