### PR TITLE
Fix `Utils::modifyRequest` dropping `ServerRequest` attributes

### LINKED ISSUE #344: The new instance of ServerRequest misses attributes from the origin one.
https://github.com/guzzle/psr7/blob/ad1de77a65b751d598ced37747bf4c17d457fbc9/src/functions.php#L238-L251

Here is possible solution. 

```php
 if ($request instanceof ServerRequestInterface) {
        $new = (new ServerRequest(
            isset($changes['method']) ? $changes['method'] : $request->getMethod(),
            $uri,
            $headers,
            isset($changes['body']) ? $changes['body'] : $request->getBody(),
            isset($changes['version'])
                ? $changes['version']
                : $request->getProtocolVersion(),
            $request->getServerParams()
        ))
        ->withParsedBody($request->getParsedBody())
        ->withQueryParams($request->getQueryParams())
        ->withCookieParams($request->getCookieParams())
        ->withUploadedFiles($request->getUploadedFiles());
        
        foreach ($request->getAttributes() as $key => $value) {
            $new = $new->withAttribute($key, $value);
        }

        return $new;
    }
```

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Fixes #344.

### CODE REVIEW

**Review by Nyholm — APPROVED** [review]
Thank you

**Comment by GrahamCampbell** [comment]
Better wait for CI before merging. I've not run the tests locally. :trollface:

**Comment by Nyholm** [comment]
> I've not run the tests locally.

I've spent all this time setting up CI... Im rarely running the tests locally.

**Comment by GrahamCampbell** [comment]
CI green now. :)

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
