### PR TITLE
.gitattributes: Add extra export-ignore entries

### PR DESCRIPTION
**Pull request by reedy**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but 1.x is in security fix mode, only.

**Comment by reedy** [comment]
Doesn't seem to be documented as such... https://github.com/guzzle/psr7/blob/master/README.md

**Comment by reedy** [comment]
It's not documented there then, it's a level deeper.

**Comment by GrahamCampbell** [comment]
It's in the standard location for this, also accessible via the security tab.

**Comment by sagikazarmark** [comment]
Hope this makes the situation cleaner: #496

TBH @GrahamCampbell I don't see why we couldn't accept this patch. It doesn't change any behavior in code, just makes the packaging process a bit cleaner. My two cents.

**Comment by GrahamCampbell** [comment]
Would be no point. I don't plan to ever do another 1.x release, unless there is a security requirement to do so, so the change would never get used by people using stable versions.

**Comment by sagikazarmark** [comment]
I see. Yeah, I guess that's a good point.

**Comment by reedy** [comment]
And then there was the 1.9 release :)

**Comment by reedy** [comment]
Yeah, I know. But if this had been merged, it would've also got released as a side effect.

**Pull request closed without merging**
