### PR TITLE
Use strict equality checks where possible

### PR DESCRIPTION
**Pull request by dave1010**
There are also a couple of tests that I'm not sure if they should be strict or weak:

In `Request::getRequestTarget()`

    if ($target == null) {

In `Uri::getPath()`

    return $this->path == null ? '' : $this->path;

I'm guessing they should return true for `null` or `""` but probably not `0` or `0.0`.

### CODE REVIEW

**Comment by mtdowling** [comment]
I had the same thoughts, but @jeremeamia says that these equality checks were made intentionally. @jeremeamia, can you elaborate?

**Comment by jeremeamia** [comment]
Yeah, the `== null` and `!= null` are intentional. This is so values like `"0"` are handled correctly. If `$value = '0'`, then `empty($value)` and `!$value` both return `true`, but `$value == null` returns `false`. Fun times with PHP types.

**Comment by dave1010** [comment]
OK, I think that makes sense for the == null. Caught me off guard though as 

    var_dump(0 == null); // true
    var_dump("0" == null); // false

IMO opinion being explicit with a strict equality check for "" or null would be clearer here. I'll update / make a new PR (ideally with tests) later if that's worth it.

The strict checks I've added in the current patch aren't against null but hints and strings so I believe are the correct behaviour.

**Comment by mtdowling** [comment]
I'd rather use the checks as they are, but just have better comments that describe why we're using null or empty, etc... Closing this PR, but I'd merge something that added comments and strict equality in other places where it doesn't rely on the tricks @jeremeamia utilized.

**Pull request closed without merging**
