### PR TITLE
Added DocBlocks in Request class methods

### PR DESCRIPTION
**Pull request by tigranmaestro**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Thanks for your contribution. I don't necessarily see a need for adding these docblocks though, as the methods are documented in the interfaces. inheritdoc tags might be useful.

WDYT @Nyholm

**Comment by Tobion** [comment]
The docs provided by the interfaces are much more complete. So this overwriting is counter productive. But thanks for trying to improve the docs.

**Comment by tigranmaestro** [comment]
@sagikazarmark @Tobion Thanks, got it.

**Comment by Nyholm** [comment]
I agree. Thank you @tigranmaestro for making this suggestion though.

**Pull request closed without merging**
