### PR TITLE
Remove deprecated function definitions

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by Nyholm** [comment]
Has this code been released as "deprecated" in 1.x?

**Comment by GrahamCampbell** [comment]
> Has this code been released as "deprecated" in 1.x?

Yes, in 1.7.0. I'd like to also do a 1.8.0 later, and soft-final all classes that are now final in 2.x. Possibly there are a few extra things we might want to deprecate too, in the interest of keeping this package small and maintainable.

**Comment by Nyholm** [comment]
Yeah, good!

**Review by Nyholm — APPROVED** [review]
Finally!

**Pull request merged**
