### PR TITLE
PHP 5.3 Compatibility

### PR DESCRIPTION
**Pull request by kirill-konshin**
What has been changed:

- `[]` arrays were replaced with `array()`
- traits were replaced with abstract classes
- 3 tests in UriTest were updated due to inconsistency in function `parse_url` before version 5.4.7 and after (but I think it's not a big deal)
- couple of `callable` declarations were removed from code (they still exist in phpdoc)
- 1 test was removed -- BadStream

No major changes, all tests are feeling good, tested under PHP 5.3.29.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1:

**Comment by jeskew** [comment]
Changing the StreamDecoratorTrait to a base class is a major backwards-compatibility break. If this were accepted, it would need to be a major version bump. Supporting an EOL'd version doesn't seem like the progress I would want to see in a 2.0.

**Comment by GrahamCampbell** [comment]
If we were going to do a major version bump, I'd want to see php 5.4 support dropped too tbh...

**Comment by jeremeamia** [comment]
@kirill-konshin It sounds like you will definitely want to keep your own fork of this project.

**Comment by GrahamCampbell** [comment]
I don't see the point in making the effort with an EOL php version.

**Comment by henriquemoody** [comment]
I think this PR is more like a courtesy of @kirill-konshin, he knows it won't be accept since Michael Dowling already said in #28:

> You should fork if you need PHP 5.3 support. Apologies, but I don't want to support 5.3 in this repo.

I think since you want to keep working with 5.3 you have to be used to use old package versions, many of the packages that people create these days don't even support 5.4.

**Comment by makasim** [comment]
:-1: 

When I was about to reuse guzzle as http client in payum (because of psr7). I was forced to use php55, and that's great.

**Comment by mtdowling** [comment]
Thanks for the PR @kirill-konshin. Like I said before, I won't merge this into the guzzlehttp/psr7 pacakge, but hopefully this PR will help others that require PHP 5.3 support to find your fork.

**Comment by kirill-konshin** [comment]
Unfortunately, some of our clients still use 5.3 and can't migrate, as well as some of the developers around. I would be glad to drop 5.3 and even 5.4 support, but it is still discussed in our company.

Regarding this PR, I was aware that there is a very small chance to be accepted :) but I don't understand why traits were chosen instead of abstract classes (as you see, they work OK) and the rest of the code base is actually 5.3 compatible (except array declarations and couple other places) so in general.

What if you guys will create a dead end branch for 5.3 in order to skip bumping of a major release version but still have something for 5.3 w/o my non-discoverable fork...

**Comment by kirill-konshin** [comment]
So how about a branch for 5.3? In this case installation, at least, will be a lot easier for people who can't find my fork. And it will not pollute the rest of the codebase. We can add an unsupported message to `README.md`. And there will be no need to bump a version.

**Comment by kirill-konshin** [comment]
Any updates regarding accepting PR into a dedicated branch? I can provide necessary support for this branch.

**Comment by jeskew** [comment]
I think keeping it in your fork is a better experience for your clients. That way, you can do tagged releases, too.

**Comment by kirill-konshin** [comment]
Is it supported by composer to give a way to load tagged release from a fork? So far I only found a way to substitute the repository.

**Comment by jeskew** [comment]
Sure. If you provide a repository in your composer.json file, [composer will pull the package from there instead of from packagist](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository).

**Comment by kirill-konshin** [comment]
That's exactly how I did it :) so in the fork I can have tags and composer will understand them? If yes, then the only thing would be -- how people will discover the fork in case they'll need 5.3...?

**Pull request closed without merging**
