### PR TITLE
Merge 1.x into master

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Note that the 1.x supports PHP 8, but master doesn't yet. This is due to a regression that needs fixing on 1.x first: https://github.com/guzzle/psr7/pull/375. We're also expecting https://github.com/http-interop/http-factory-tests/pull/46 to be merged and tagged as 0.9.0 or 1.0.0.

### CODE REVIEW

**Comment by bbrala** [comment]
@GrahamCampbell can you ping here when you think this is done? Then i can go through the changes, i already did al the work once so that might help. :)

**Comment by GrahamCampbell** [comment]
This is done. That's why the PR is not marked as WIP. :)

**Comment by GrahamCampbell** [comment]
This PR is purely a merge, so no deprecated code has been removed. That will happen in a follow-up.

**Comment by bbrala** [comment]
Yeah kinda assumed that when i was looking through the code, there is a few issues that need fixing after this :)

**Review by Nyholm — APPROVED** [review]
Make sure to not squash the commits when merging.

**Pull request merged**
