### PR TITLE
Fix case where the user info are added dispite empty

### PR DESCRIPTION
**Pull request by gmponos**
Check failing test [here](https://travis-ci.org/guzzle/guzzle/jobs/553448024) , https://github.com/guzzle/guzzle/pull/2327

### CODE REVIEW

**Comment by Tobion** [comment]
This is not according to rfc 3986

> Applications should not render as clear text any data
   after the first colon (":") character found within a userinfo
   subcomponent unless the data after the colon is the empty string
   (indicating no password)

**Comment by gmponos** [comment]
I am not sure if I follow. At the moment if I do something like this:

```
        $uri = (new Uri('http://example.org/path'))->withUserInfo('', '');
        echo (string)$uri;
```

It will output `http://:@example.org/path`

Is this correct?

**Comment by Tobion** [comment]
`http://:@example.org/path` is a valid URI and browsers do accept it as well. It's basic auth with empty username and no password. There is not much use to it but it's valid.
Why not call `withUserInfo('', null)`? That would be the right thing to do as the default for password is null which means, no password.

**Comment by gmponos** [comment]
Thank you.. I did not knew about this. I pushed a fixed to Guzzle client at the PR I mentioned above..

**Comment by sagikazarmark** [comment]
@Tobion this still seems to be a regression to me (as mentioned in #290), but I'm inclined to leave it as is if there is no real case where this can cause problems (except in the breaking tests).

**Pull request closed without merging**
