### PR TITLE
Run CI with PHP 8.2

### PR DESCRIPTION
**Pull request by TimWolla**

### CODE REVIEW

**Comment by TimWolla** [comment]
Side note: The branch protection should probably be configured to require PHP 8.0 and 8.1 to apss.

**Comment by GrahamCampbell** [comment]
Before we merge this, we should understand why the tests don't fail, given https://github.com/guzzle/psr7/issues/482.

**Comment by TimWolla** [comment]
@GrahamCampbell “Fixed”

**Comment by TimWolla** [comment]
Green now after merge of master, red previously.

**Pull request merged**
