### PR TITLE
do not try to trim streams in MessageTrait.php

### PR DESCRIPTION
**Pull request by bong0**

### CODE REVIEW

**Comment by Tobion** [comment]
A header must be a string according to psr7 interface. So what is the use-case here?

**Comment by bong0** [comment]
If I do something like this:

    return new Request('POST', 'http://.../write?db=o&precision=s', [
        'body' => $stream
    ]);

the following appears:

    PHP Warning:  trim() expects parameter 1 to be string, resource given in 
    /home/bongo/dev/vendor/guzzlehttp/psr7/src/MessageTrait.php on line 184

appears

**Comment by Tobion** [comment]
The third param of Request constructor are the headers. So you are passing the wrong data. You probably confuse it with `$guzzle->request` which accepts options. See http://docs.guzzlephp.org/en/stable/request-options.html#body
But that is something different from the request constructor.

**Comment by bong0** [comment]
@Tobion Yes, thanks for the clarification. I am passing the wrong data since I confused the two arrays. It was a sort of desperate try to make it work this way since I just couldn't find any doc on the Request class. Am I seeing this right or did I miss something?

**Comment by Tobion** [comment]
http://docs.guzzlephp.org/en/stable/psr7.html

**Pull request closed without merging**
