### PR TITLE
Fix erroneous behaviour when combining host and relative path

### LINKED ISSUE #531: Relative path with authority part present fails
Why relative paths forbidden when authority part is present?

https://github.com/guzzle/psr7/blob/69568e4293f4fa993f3b0e51c9723e1e17c41379/tests/UriTest.php#L599-L605

This violates [withPath](https://github.com/php-fig/http-message/blob/efd67d1dc14a7ef4fc4e518e7dee91c271d524e4/src/UriInterface.php#L242-L264) contract. Also there's [clear description](https://github.com/php-fig/http-message/blob/efd67d1dc14a7ef4fc4e518e7dee91c271d524e4/src/UriInterface.php#L312-L313) how to avoid problem described in the aforementioned code comment.

### PR DESCRIPTION
**Pull request by onyn**
Fixes #531

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks.

**Comment by Tobion** [comment]
This is wrong and must be reverted. How can this be accepted changing an explicit test without referencing the lenghty discussions we already had about this and the RFC ammendments that were proposed.

**Comment by Tobion** [comment]
There is even a deprecation in 1.x about this: https://github.com/guzzle/psr7/blob/e98e3e6d4f86621a9b75f623996e6bbdeb4b9318/src/Uri.php#L801-L807

**Comment by GrahamCampbell** [comment]
There was a discussion in Slack about this (unfortunately no longer accessible because of the 90 day retention). It was decided that both the previous and updated implementation were wrong, since the previous implementation disallowed too much, and the new implementation allows too much, and that we'd rather allow too much where it's not too harmful to do so. I don't remember the specific cases I'm afraid.

**Comment by GrahamCampbell** [comment]
If you feel strongly about this, I don't oppose reverting this. I am pretty neutral either way.

**Comment by Tobion** [comment]
Yes I feel strongly about it because it violates RFC 3986 by not forming a valid URI. The workarounds mentioned in PSR-7 are only artifacts e.g. due to old PHP version not supporting throwing exceptions in __toString. But those workarounds have already been deprecated in 1.x. It does not make any sense to revert this again. Then the whole deprecation is pointless.

**Comment by GrahamCampbell** [comment]
Then we could revert this and say this was a bug we introduced in 1.4.2, and we're fixing it again in 1.4.5.

**Pull request merged**
