### PR TITLE
Avoid no uri index in stream_get_meta_data

### LINKED ISSUE #411: Can't send file from stream_type MEMORY
**PHP version**: 7.3.27 (hint: `php --version`)

**Description**
```
Undefined index: uri in /app/vendor/guzzlehttp/psr7/src/Utils.php:320
```

`\stream_get_meta_data($resource)` return
```
array (
  'timed_out' => false,
  'blocked' => true,
  'eof' => false,
  'stream_type' => 'MEMORY',
  'mode' => 'rb',
  'unread_bytes' => 0,
  'seekable' => true,
)
```

**How to reproduce**

1. read 0 bytes from `bytea` field of table with `ActiveRecord` `yii2` 
(as resource from \PDOStatement::execute(); \PDOStatement::fetch(); see https://www.php.net/manual/en/class.pdostatement.php )
2. send as multipart file this resource

**Possible Solution**

```
                $metaData = \stream_get_meta_data($resource);
                if (array_key_exists('uri', $metaData) && $metaData['uri'] === 'php://input') {
```
or
```
                if (\stream_get_meta_data($resource)['uri'] ?? '' === 'php://input') {
```
**Additional context**

### PR DESCRIPTION
**Pull request by bscheshirwork**
fix #411

### CODE REVIEW

**Comment by bscheshirwork** [comment]
so hard to repeat no-url index in separated case (((

I try somthing like 
```
        $thing = <<<TEST
someData
TEST;
        $filename = "php://memory";
        $fp = fopen($filename, "w+b");
        fwrite($fp, $thing);
        rewind($fp);

        $metaData = \stream_get_meta_data($fp);

        $pdo = new \PDO(
            'sqlite::memory:',
            null,
            null,
            [\PDO::ATTR_PERSISTENT => true]
        );
        $pdo->exec("create table `file_storage` ( `data` bytea )");
        $sql = $pdo->prepare("INSERT INTO `file_storage` (`data`) VALUES (:data)");
        $sql->bindValue(':data', $fp, \PDO::PARAM_LOB);
        $sql->execute();

        $stmt = $pdo->query("SELECT * FROM file_storage LIMIT 1");
        $row = $stmt->fetch(\PDO::FETCH_ASSOC);
        $metaData = \stream_get_meta_data($row['data']);

        $response = $this->client->post('etl',
            [
                RequestOptions::MULTIPART => [
                    [
                        'Content-type' => 'multipart/form-data',
                        'name' => 'file',
                        'filename' => 'name',
                        'contents' => $fp,
                    ]
                ],
            ]
        );

```

but I nave nomore time to try(((

**Comment by bscheshirwork** [comment]
https://github.com/guzzle/psr7/commit/202292ec8bf0fdf3d80bf3d84ef877acbaecbefb

**Comment by GrahamCampbell** [comment]
@Nyholm I'd like to merge this fix on 1.x.

**Comment by Nyholm** [comment]
Yes. That make sense. 

@bscheshirwork could you make a second PR targeting 1.x?

**Comment by GrahamCampbell** [comment]
Closing in favour of https://github.com/guzzle/psr7/pull/413. I will branch merge 1.x -> master after the next 1.x release.

**Pull request closed without merging**
