### PR TITLE
[2.0] Avoid functions due to global install conflicts

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Left all the functions in, like for my Guzzle 7 PR, but just made sure that the "core code" doesn't actually use tem.

### CODE REVIEW

**Comment by Tobion** [comment]
Can you elaborate the reasoning? I don't like the functions either. But putting them in a generic Utils namespace is not good either. They should be grouped into reasonable classes like I did for UriNormalizer, UriResolver etc.

**Comment by gmponos** [comment]
https://github.com/guzzle/guzzle/issues/2511

This is the root of the current PR.

**Comment by GrahamCampbell** [comment]
@Tobion Yeh, the problem is that if the same package is installed globally, with a different version, then we can get wrong functions defined. The best way to avoid this is to use static class methods. Loading of classes is delayed until they are needed at runtime.

**Comment by GrahamCampbell** [comment]
> But putting them in a generic Utils namespace is not good either.

It's no worse, but it does fix the bug we are trying to fix. We could also group the functions into classes if we wanted, but that's not needed to address the issue. ;)

**Comment by GrahamCampbell** [comment]
I am going to implement the `Utils` class for 1.7.0, and deprecate the global functions. That way Guzzle 7.1.0 can use it.

**Pull request closed without merging**
