### PR TITLE
Added more entropy to uniqid

### PR DESCRIPTION
**Pull request by lyrixx**
cf http://blog.kevingomez.fr/til/2015/07/26/why-is-uniqid-slow/

### CODE REVIEW

**Comment by Nyholm** [comment]
Thank you for this PR. I cannot merge this in the current state though... According to [RFC2046](https://tools.ietf.org/html/rfc2046#section-5.1.1) a valid boundary is: 
```
     boundary := 0*69<bchars> bcharsnospace
     bchars := bcharsnospace / " "
     bcharsnospace := DIGIT / ALPHA / "'" / "(" / ")" /
                      "+" / "_" / "," / "-" / "." /
                      "/" / ":" / "=" / "?"
```

Be aware that: 

```php
echo uniqid();            // 589c62cd00001
echo uniqid('', true);  //589c62cd000005.45285185
```

The tricky part is the extra period that this PR introduces. The RFC says that such bounderies must be quoted.

The following is not valid:
```
Content-Type: multipart/mixed; boundary=gc0pJq0M.08jU534c0p
```
and must instead be represented as:
```
Content-Type: multipart/mixed; boundary="gc0pJq0M.08jU534c0p"
```

We are not quoting at all currently. We should make sure to quote the boundary where ever we are using it.

**Comment by lyrixx** [comment]
Or I can simply hash the boundary ?

**Comment by Nyholm** [comment]
Sure, I created a small script to measure times. Here is the output: 
```
uniqid():         11.343955993652 ms
uniqid('', true): 1.3971328735352 ms
sha1:             2.5057792663574 ms
md5:              2.4011135101318 ms
base64_decode:    2.471923828125 ms
```

"sha1" means `sha1(uniqid('', true))`

So yes, Sure. Hashing makes sense, It will work and you will get the speed performance.

**Comment by lyrixx** [comment]
PR Updated.

**Comment by sagikazarmark** [comment]
This is great, thanks.

**Comment by nicholasruunu** [comment]
@Nyholm You who are so fuzzy about performance didn't try `str_replace('.', '', uniqid('', true))`? 😛

**Pull request merged**
