### PR TITLE
1.x simplify conditional

### PR DESCRIPTION
**Pull request by hendeavors**
Small revision to simplify conditional logic.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎 This changes the side effects of the function.

**Comment by Tobion** [comment]
@GrahamCampbell what do you mean?

**Comment by GrahamCampbell** [comment]
Your new code writes `Host` to `$this->headerNames['host']`. The old code did not.

**Comment by Tobion** [comment]
The current code does that too: https://github.com/guzzle/psr7/blob/3472035ddb363a8452bc6999eeb92a92985879d7/src/Request.php#L141

**Comment by Tobion** [comment]
But it's not worth anyway as it does an extra array lookup `$this->headerNames['host']`.

**Pull request closed without merging**
