### PR TITLE
Add reason phrase for 308 http status code

### LINKED ISSUE #341: Add http status code 308 (Permanent Redirect)
Noticed that [Response.php](https://github.com/guzzle/psr7/blob/master/src/Response.php) missing http status code 308 (Permanent Redirect) that was introduced in [RFC7538](https://tools.ietf.org/html/rfc7538).

### PR DESCRIPTION
**Pull request by onyn**
Closes #341.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
@Tobion do we want to include this in a 1.9.0 release, or just keep on 2.x?

**Comment by Nyholm** [comment]
Let's only make changes to 1.x if they are serious bugs.

**Review by GrahamCampbell — APPROVED** [review]

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
Could you include a test please?

**Comment by onyn** [comment]
What kind of test you wanted to see? Currently there is no any tests that checks correctness of reason phrase. The only test I can imagine:

```php
    public function test308PermanentRedirect(): void
    {
        $response = new Response(308);
        self::assertSame('Permanent Redirect', $response->getReasonPhrase());
    }
```

I think it's a bit useless. But if you want, I can push it.

**Review by Tobion — APPROVED** [review]

**Review by Nyholm — APPROVED** [review]
I'll @GrahamCampbell decide if that test is needed. Im fine with and without it.

**Review by GrahamCampbell — APPROVED** [review]

**Pull request merged**
