### PR TITLE
Fix `Message::bodySummary` when `preg_match` fails

### PR DESCRIPTION
**Pull request by XilefNori**
preg_replace returns "false" on failure which interpreted as OK result which is wrong.
Reform statement in positive manner makes it right

### CODE REVIEW

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
I think the right fix here is just to add a `=== 0`?

**Comment by XilefNori** [comment]
> I think the right fix here is just to add a `=== 0`?

No. Cause you still have to check false.

```php
$hasNoBadChars = preg_match('/[\pL\pM\pN\pP\pS\pZ\n\r\t]/u', $summary);
if ($hasNoBadChars === 0 || $hasNoBadChars === false) {
    return null;
}
```

And I'm not sure if it looks better the sample I suggested first.

**Comment by XilefNori** [comment]
> I think the right fix here is just to add a `=== 0`?

I guess you right

**Review by jtojnar — CHANGES_REQUESTED** [review]
❌ If we did as you suggest, the function might return non-printable bytes when `preg_match` is “broken”. Note that the documentation specifically says “Will return `null` if the response is not printable.” and we just cannot tell without `preg_match`.

By the way, how does `preg_match` even break?

**Comment by XilefNori** [comment]
> By the way, how does `preg_match` even break?

For example when you has utf-8 malformed symbol in tested string (which you get when cut utf-8 string code in the middle of multibyte UTF character).

> ❌ If we did as you suggest, the function might return ç when `preg_match` is “broken”. Note that the documentation specifically says “Will return `null` if the response is not printable.” and we just cannot tell without `preg_match`.

No, it will not. When  preg_match breaks you get `false` (`!== 0`),  therefore it will return `null`.

```php
if (preg_match('/[^\pL\pM\pN\pP\pS\pZ\n\r\t]/u', $summary) === 0) {
    return $summary;
}

return null;
```

**Comment by jtojnar** [comment]
> No, it will not. When preg_match breaks you get `false` (`!== 0`), therefore it will return `null`.

Right, but that is precisely what I would expect based on “Will return null if the response is not printable.” UTF-8 malformed symbol is not printable.

**Comment by jtojnar** [comment]
Turns out I was misunderstanding you. It was previously returning a malformed UTF-8 and your change makes it return `null`. I added a test: https://github.com/guzzle/psr7/pull/559

**Pull request merged**
